/// <reference types="react" />
import { ColorValue } from 'react-native';
type propTypes = {
    item: itemType;
    height: number;
    minHeight: number;
    opacity?: number;
    animationDuration: number;
    roundedTop: Boolean;
    roundedBottom: Boolean;
    barWidth: number;
    gradientColor: ColorValue;
    frontColor: ColorValue;
    noGradient?: Boolean;
    noAnimation?: Boolean;
    cappedBars?: Boolean;
    capThickness?: number;
    capColor?: ColorValue;
    capRadius?: number;
    horizontal: Boolean;
    intactTopLabel: Boolean;
    barBorderRadius?: number;
    containerHeight?: number;
    maxValue?: number;
    barBackgroundPattern?: Function;
    patternId?: String;
    barMarginBottom?: number;
    barStyle?: object;
};
type itemType = {
    value?: number;
    onPress?: any;
    frontColor?: ColorValue;
    sideColor?: ColorValue;
    topColor?: ColorValue;
    showGradient?: Boolean;
    gradientColor?: any;
    label?: String;
    barWidth?: number;
    labelTextStyle?: any;
    topLabelComponent?: Function;
    topLabelContainerStyle?: any;
    disablePress?: any;
    capThickness?: number;
    capColor?: ColorValue;
    capRadius?: number;
    barBorderRadius?: number;
    barBackgroundPattern?: Function;
    patternId?: String;
    barMarginBottom?: number;
    barStyle?: object;
};
declare const Animated2DWithGradient: (props: propTypes) => JSX.Element;
export default Animated2DWithGradient;
