/// <reference types="node" />
import { Component } from 'react';
import { ColorValue } from 'react-native';
import { Style } from 'util';
type Props = {
    style?: any;
    width?: number;
    height?: number;
    minHeight?: number;
    color?: ColorValue;
    showGradient?: Boolean;
    gradientColor?: any;
    frontColor?: ColorValue;
    sideColor?: ColorValue;
    topColor?: ColorValue;
    topLabelComponent?: Component;
    topLabelContainerStyle?: Style;
    opacity?: number;
    side?: String;
    labelTextStyle?: any;
    item: itemType;
    index: number;
    label: String;
    containerHeight?: number;
    maxValue: number;
    spacing?: number;
    propSpacing?: number;
    data?: any;
    barWidth?: number;
    sideWidth?: number;
    labelWidth?: number;
    isThreeD?: Boolean;
    isAnimated?: Boolean;
    rotateLabel?: Boolean;
    animatedHeight?: any;
    appearingOpacity?: any;
    animationDuration?: number;
    roundedTop?: Boolean;
    roundedBottom?: Boolean;
    disablePress?: Boolean;
    activeOpacity?: number;
    cappedBars?: Boolean;
    capThickness?: number;
    capColor?: ColorValue;
    capRadius?: number;
    showXAxisIndices: Boolean;
    xAxisIndicesHeight: number;
    xAxisIndicesWidth: number;
    xAxisIndicesColor: ColorValue;
    horizontal: Boolean;
    intactTopLabel: Boolean;
    barBorderRadius?: number;
    autoShiftLabels?: Boolean;
    barBackgroundPattern?: Function;
    patternId?: String;
    barMarginBottom?: number;
    onPress?: Function;
    xAxisTextNumberOfLines: number;
    renderTooltip: Function;
    leftShiftForTooltip?: number;
    leftShiftForLastIndexTooltip: number;
    initialSpacing: number;
    selectedIndex: number;
    setSelectedIndex: Function;
    barStyle?: object;
};
type itemType = {
    value?: number;
    onPress?: any;
    frontColor?: ColorValue;
    sideColor?: ColorValue;
    topColor?: ColorValue;
    showGradient?: Boolean;
    gradientColor?: any;
    label?: String;
    barWidth?: number;
    sideWidth?: number;
    labelTextStyle?: any;
    topLabelComponent?: Function;
    topLabelContainerStyle?: any;
    disablePress?: any;
    capThickness?: number;
    capColor?: ColorValue;
    capRadius?: number;
    labelComponent?: Function;
    barBorderRadius?: number;
    topLabelComponentHeight?: number;
    spacing?: number;
    labelWidth?: number;
    barBackgroundPattern?: Function;
    patternId?: String;
    barMarginBottom?: number;
    leftShiftForTooltip?: number;
    barStyle?: object;
};
declare const RenderBars: (props: Props) => JSX.Element;
export default RenderBars;
